# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camlxz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1428, 745)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 40, 641, 481))
        self.label.setObjectName("label")
        self.button_open_camera = QtWidgets.QPushButton(Form)
        self.button_open_camera.setGeometry(QtCore.QRect(820, 600, 93, 71))
        self.button_open_camera.setStyleSheet("开始录制")
        self.button_open_camera.setObjectName("button_open_camera")
        self.button_close = QtWidgets.QPushButton(Form)
        self.button_close.setGeometry(QtCore.QRect(1040, 600, 93, 71))
        self.button_close.setObjectName("button_close")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(720, 40, 491, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "                                    界面显示"))
        self.button_open_camera.setText(_translate("Form", "开始录制"))
        self.button_close.setText(_translate("Form", "结束"))
        item = self.tableWidget.horizontalHeaderItem(0)

        item.setText(_translate("Form", "目标ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "数量"))
